sourceSets.main.java.srcDirs = [ "src/" ]

sourceCompatibility = '1.8'
[compileJava, compileTestJava]*.options*.encoding = 'UTF-8'

ext {
	mainClassName = "jm.games.nebula.IOSLauncher"
}

launchIPhoneSimulator.dependsOn build
launchIPadSimulator.dependsOn build
launchIOSDevice.dependsOn build
createIPA.dependsOn build


robovm {
	archs = "arm64"
	iosSignIdentity = "Apple Distribution: James Macre (ZG76X575A5)"
	iosProvisioningProfile = "jm.games.nebula"
	iosSkipSigning = false
}
dependencies {
	implementation "io.github.dkimitsa.robovm:robopods-firebase-google-mobile-ads-ios:$altpodsVersion"
	implementation "com.badlogicgames.gdxpay:gdx-pay-iosrobovm-apple:$gdxPayVersion"
	implementation "pl.mk5.gdx-fireapp:gdx-fireapp-core:$gdxFireappVersion"
	implementation "pl.mk5.gdx-fireapp:gdx-fireapp-ios:$gdxFireappVersion"
}

eclipse.project.name = appName + "-ios"
