sourceSets.main.java.srcDirs = [ "src/" ]

sourceCompatibility = '1.8'
[compileJava, compileTestJava]*.options*.encoding = 'UTF-8'

ext {
	mainClassName = "IOSLauncher"
}

launchIPhoneSimulator.dependsOn build
launchIPadSimulator.dependsOn build
launchIOSDevice.dependsOn build
createIPA.dependsOn build


robovm {
	archs = "thumbv7:arm64"
	iosSignIdentity = "Apple Distribution: James Macre (ZG76X575A5)"
	iosProvisioningProfile = "jm.games.nebuladist"
	iosSkipSigning = false
	archs = "thumbv7:arm64"
}
dependencies {
	implementation "io.github.dkimitsa.robovm:robopods-firebase-google-mobile-ads-ios:$altpodsVersion"
}

eclipse.project.name = appName + "-ios"
